### PR TITLE
Support Nextcloud v25 - v27

### PR DESCRIPTION
**Pull request by grubersjoe**
Markup has changed with v28

### CODE REVIEW

**Comment by grubersjoe** [comment]
@pjft okay I released this in the Nextcloud App Store under v1.0.5. Can you please test if this works in your Nextcloud? I only have a v28 running...

**Comment by grubersjoe** [comment]
And v28 only is supported in v1.0.6 now.

**Comment by pjft** [comment]
Thank you! I see it on the browser but can't download it yet on my instance for some reason. I'll wait for tomorrow to see if the update shows up. Uninstalling the app and reinstalling only gets 1.0.4 so it might be some sort of updater that needs to run here. I'll let you know how it goes!

**Comment by pjft** [comment]
Good morning! I have updated now to 1.0.5 and it does seem to work as intended, unless for some reason my manual fixes to 1.0.4 are still cached :)

Thank you!

**Comment by grubersjoe** [comment]
Great! Thanks for testing!

**Pull request merged**
